"""
Django settings for redTI project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def base_dir_join(*args):
    return os.path.join(BASE_DIR, *args)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9vukhln#(+^mg(wb_0%hwoact@ehd(wj5#3evbc)^0(luqw0i6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'users.User'#usado por a gente ter criado um personalizado

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'users',
    'subs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'redTI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [base_dir_join('templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contribhttps://github.com/lucas625/FAI-2019.git.messages.context_processors.messages',
            ],https://github.com/lucas625/FAI-2019.git
        },https://github.com/lucas625/FAI-2019.git
    },https://github.com/lucas625/FAI-2019.git
]https://github.com/lucas625/FAI-2019.git
https://github.com/lucas625/FAI-2019.git
WSGI_APPLICATION = 'redTI.wsgi.https://github.com/lucas625/FAI-2019.gitapplication'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {https://github.com/lucas625/FAI-2019.git
     https://github.com/lucas625/FAI-2019.gitb.auth.password_validation.NumericPasswordValidator',
    }https://github.com/lucas625/FAI-2019.git
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = Truehttps://github.chttps://github.com/lucas625/FAI-2019.gitom/lucas625/FAI-2019.git
https://github.com/lucas625/FAI-2019.git
USE_TZ = Truehttps://github.com/lucas625/FAI-2019.git
https://github.com/lucas625/FAI-2019.git
https://github.com/lucas625/FAI-2019.git
# Static files https://github.chttps://github.com/lucas625/FAI-2019.gitom/lucas625/FAI-2019.git Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


STATIC_ROOT = base_dir_join('staticfiles')
#esse base_dir_join fala que além da pasta padrão, teremos esta outra também
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    base_dir_join('assets'),
)
MEDIA_ROOT = base_dir_join('mediafiles')
MEDIA_URL = '/media/'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'